### ISSUE TITLE
vaapi decoding not available: trying to use libva.so.1 but Flatpak runtime only has libva.so.2

### ISSUE THREAD

**Issue by thor2002ro** [flathub/com.valvesoftware.SteamLink#12]
intel laptop gen9 gpu 

INFO: CVDPAUAccel: GL_NV_vdpau_interop not available on current context
INFO: CVAAPIAccel: Couldn't load libva.so.1
INFO: libavcodec software decoding with 2 threads

amd laptop 3500u

Failed to open VDPAU backend libvdpau_radeonsi.so: cannot open shared object file: No such file or directory
INFO: ffmpeg error: VDPAU device creation on X11 display :99.0 failed.
INFO: CVDPAUAccel: av_hwdevice_ctx_create() failed
INFO: CVAAPIAccel: Couldn't load libva.so.1
INFO: libavcodec software decoding with 4 threads

both have video acceleration working tested in chromium and vlc(running under flatpak)
both X11

**Comment by smcv** [comment]
This is a known issue and being looked at. A future version will hopefully use the more modern `libva.so.2` instead.

**Comment by thor2002ro** [comment]
ok..... I got somewhere... 

it seams it needs the library linking fix as steam.....

ln -s libva.so.2 libva.so.1
ln -s libva-x11.so.2 libva-x11.so.1

in the main runtime....
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/20.08/xxxxx/files/lib/x86_64-linux-gnu

and all started working ..... but was a little laggy because it was using the "new" iHD driver
logs:

> INFO: Opened audio device: format=2, channels=2, frequency=48000
> INFO: Initialized audio decoder: codec=3, sample rate=48000, channels=2
> INFO: Got control packet k_EStreamControlStartAudioData
> INFO: Got control packet k_EStreamControlSetSpectatorMode
> INFO: Got control packet k_EStreamControlSetCaptureSize
> INFO: Got control packet k_EStreamControlSetTitle
> INFO: Got control packet k_EStreamControlSetIcon
> INFO: Got control packet k_EStreamControlSetCursor
> INFO: Got control packet k_EStreamControlSetKeymap
> INFO: Got control packet k_EStreamControlSetActivity
> INFO: Got control packet k_EStreamControlSetCursorImage
> INFO: Got control packet k_EStreamControlStartVideoData
> INFO: Got control packet k_EStreamControlVideoEncoderInfo
> INFO: CVDPAUAccel: GL_NV_vdpau_interop not available on current context
> INFO: ffmpeg verbose: Opened VA display via X11 display :99.0.
> libva info: VA-API version 1.8.0
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so
> libva info: Found init function __vaDriverInit_1_8
> libva info: va_openDriver() returns 0
> INFO: ffmpeg verbose: Initialised VAAPI connection: version 1.8
> INFO: ffmpeg verbose: Unknown driver "Intel iHD driver for Intel(R) Gen Graphics - 20.3.0 ()", assuming standard behaviour.
> INFO: VAAPI hardware decoding
> INFO: ffmpeg verbose: Reinit context to 1920x1088, pix_fmt: vaapi_vld
> INFO: Got control packet k_EStreamControlVideoEncoderInfo
> INFO: Marking frame 1 complete with status k_EStreamFrameResultDroppedLate
> INFO: Marking frame 2 complete with status k_EStreamFrameResultDroppedLate
> INFO: Marking frame 3 complete with status k_EStreamFrameResultDroppedLate
> INFO: Targeting 29.88 FPS
> INFO: Got control packet k_EStreamControlSetTargetFramerate
> INFO: Video rect: 1920x1080 at 0,0
> INFO: Texture rect: 1920x1080 at 0,0
> INFO: Video size: 1920x1080, output size: 1920x1080, overlay size: 1920x1080
> INFO: Video rect: 1920x1080 at 0,0
> INFO: Texture rect: 1920x1080 at 0,0
> INFO: Video rect: 1920x1080 at 0,0
> INFO: Texture rect: 1920x1080 at 0,0

ignore the 30fps bad wifi at work

running with "LIBVA_DRIVER_NAME=i965 flatpak run --verbose com.valvesoftware.SteamLink"
gets me pretty close....
log:

> INFO: Got control packet k_EStreamControlStartVideoData
> INFO: Got control packet k_EStreamControlVideoEncoderInfo
> INFO: Got control packet k_EStreamControlVideoEncoderInfo
> INFO: CVDPAUAccel: GL_NV_vdpau_interop not available on current context
> INFO: ffmpeg verbose: Opened VA display via X11 display :99.0.
> libva info: Open new log file 1.110840.thd-0x00000002 for the thread 0x00000002
> libva info: LIBVA_TRACE is on, save log into 1.110840.thd-0x00000002
> libva info: VA-API version 1.8.0
> libva info: User environment variable requested driver 'i965'
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/i965_drv_video.so
> libva info: Found init function __vaDriverInit_1_8
> libva info: va_openDriver() returns 0
> INFO: ffmpeg verbose: Initialised VAAPI connection: version 1.8
> INFO: ffmpeg verbose: Matched "Intel i965 driver for Intel(R) Gemini Lake - 2.4.1" as known driver "Intel i965 (Quick Sync)".
> INFO: VAAPI hardware decoding
> libva info: Open new log file 1.110840.thd-0x0000001c for the thread 0x0000001c
> libva info: Save context 0x02000000 into log file 1.110840.thd-0x0000001c
> INFO: ffmpeg verbose: Reinit context to 1920x1088, pix_fmt: vaapi_vld
> INFO: Marking frame 0 complete with status k_EStreamFrameResultDroppedLate
> INFO: Marking frame 2 complete with status k_EStreamFrameResultDroppedLate
> INFO: Targeting 29.88 FPS
> INFO: Got control packet k_EStreamControlSetTargetFramerate
> INFO: Marking frame 6 complete with status k_EStreamFrameResultDroppedLate
> INFO: Video rect: 1920x1080 at 0,0
> INFO: Texture rect: 1920x1080 at 0,0
> INFO: Video size: 1920x1080, output size: 1920x1080, overlay size: 1920x1080
> INFO: Video rect: 1920x1080 at 0,0
> INFO: Texture rect: 1920x1080 at 0,0
> INFO: Video rect: 1920x1080 at 0,0
> INFO: Texture rect: 1920x1080 at 0,0
> INFO: Targeting 14.94 FPS
> INFO: Got control packet k_EStreamControlSetTargetFramerate
> INFO: Marking frame 34 complete with status k_EStreamFrameResultDroppedLate
> INFO: Flushing audio, 120 ms queued, 116 ms maximum, delivery delay = 8
> INFO: Targeting 29.88 FPS

not as laggy and usable.... but still need to figure out why hvec is still "not supported"...

vainfo:

> vainfo: VA-API version: 1.10 (libva 2.10.0)
> vainfo: Driver version: Intel i965 driver for Intel(R) Gemini Lake - 2.4.1
> vainfo: Supported profile and entrypoints
>       VAProfileMPEG2Simple            :	VAEntrypointVLD
>       VAProfileMPEG2Main              :	VAEntrypointVLD
>       VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
>       VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
>       VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
>       VAProfileH264Main               :	VAEntrypointVLD
>       VAProfileH264Main               :	VAEntrypointEncSlice
>       VAProfileH264Main               :	VAEntrypointEncSliceLP
>       VAProfileH264High               :	VAEntrypointVLD
>       VAProfileH264High               :	VAEntrypointEncSlice
>       VAProfileH264High               :	VAEntrypointEncSliceLP
>       VAProfileH264MultiviewHigh      :	VAEntrypointVLD
>       VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
>       VAProfileH264StereoHigh         :	VAEntrypointVLD
>       VAProfileH264StereoHigh         :	VAEntrypointEncSlice
>       VAProfileVC1Simple              :	VAEntrypointVLD
>       VAProfileVC1Main                :	VAEntrypointVLD
>       VAProfileVC1Advanced            :	VAEntrypointVLD
>       VAProfileNone                   :	VAEntrypointVideoProc
>       VAProfileJPEGBaseline           :	VAEntrypointVLD
>       VAProfileJPEGBaseline           :	VAEntrypointEncPicture
>       VAProfileVP8Version0_3          :	VAEntrypointVLD
>       VAProfileVP8Version0_3          :	VAEntrypointEncSlice
>       VAProfileHEVCMain               :	VAEntrypointVLD
>       VAProfileHEVCMain               :	VAEntrypointEncSlice
>       VAProfileHEVCMain10             :	VAEntrypointVLD
>       VAProfileHEVCMain10             :	VAEntrypointEncSlice
>       VAProfileVP9Profile0            :	VAEntrypointVLD
>       VAProfileVP9Profile0            :	VAEntrypointEncSlice
>       VAProfileVP9Profile2            :	VAEntrypointVLD

**Comment by smcv** [comment]
> ```
> ln -s libva.so.2 libva.so.1
> ln -s libva-x11.so.2 libva-x11.so.1
> ```

I wouldn't recommend this. Libraries that have different SONAMEs are not binary-compatible (that's the purpose of bumping the SONAME), so if this is working for you, it's more through luck than design.

The correct fix for this is for the proprietary executable to be changed so it loads `libva.so.2` instead of `libva.so.1`, which will involve checking that all the places where it calls into VA-API are using the new ABI (or an ABI that happens to be the same between version 1 and version 2). This cannot be done by the open source community, it has to be done internally by Valve.

**Comment by thor2002ro** [comment]
hate to tell you this but steam has been like this for years... and this is still "the fix" if you want hardware decoding with vaapi.... valve wont fix it.... 
I know its not technically correct... but I would assume people would want a working app me included :)

your choice.... I will post if I figure out hevc

**Comment by smcv** [comment]
Hardware encoding now works on `radeonsi` without any special workarounds.

It doesn't seem to get used on an Intel laptop, but that seems more likely to be a problem with the Flatpak runtime's available VA-API drivers than a problem with this app specifically.
