### ISSUE TITLE
Add support for VirtualHere

### ISSUE THREAD

**Issue by harb88** [flathub/com.valvesoftware.SteamLink#59]
I'm unsure if this is the right place to post this, but I am unable to get VirtualHere to work with this version of Steam Link. I have installed the VirtualHere server and it appears to be working fine but Steam Link doesn't show VirtualHere in the options.

**Comment by kisak-valve** [comment]
Hello @harb88, noted at https://github.com/flathub/com.valvesoftware.SteamLink#support, please use the forums (https://steamcommunity.com/app/353380/discussions/10/) for general Steam Linux feedback and troubleshooting.
