### ISSUE TITLE
Add Aarch64 Builds to Flathub

### ISSUE THREAD

**Issue by aenertia** [flathub/com.valvesoftware.SteamLink#62]
As per title only x86_64 architecture is available via flathub. Given the prevlance of rk3588 and similar aarch64 devices which support hvec/av1/h264 hardware decoding, providing the aarch64 build for these via the flathub portal would be useful.

**Comment by kisak-valve** [comment]
Hello again @aenertia, as previously noted at https://github.com/ValveSoftware/steamlink-sdk/issues/36, https://github.com/flathub/com.valvesoftware.SteamLink#support notes that feature requests are not tracked here. Please use the forums.
