### ISSUE TITLE
main/master branch is not the default

### ISSUE THREAD

**Issue by Danik1601** [flathub/com.valvesoftware.SteamLink#67]
The main/master branch is not the default on GitHub, so every commit of the stable version release goes there for some reason. And it seems like Flathub reads manifest from the master branch which is currently stuck on version 1.2.0.241, so does Steam Link on Flathub. Thus, versions 1.3.x are not available for Linux users.

**Comment by slouken** [comment]
That's correct, the 1.3.x versions are available on the beta channel.
https://steamcommunity.com/app/353380/discussions/10/3812911928394139865/
