### ISSUE TITLE
Windowed client mode?

### ISSUE THREAD

**Issue by schtufbox** [flathub/com.valvesoftware.SteamLink#8]
Is it possible to enable a windowed mode for steamlink?
I don't mean the streamed app I mean the client itself.  
I tend to run games in a windowed mode in my desktop and if you could open steamlink itself in a 1920x1080 window or 2560x1440 or similar and scaled from the host pc's 1920x1080 that would be amazing.
I hope you get what I mean? The game/app would still be running fullscreen on the host PC, but the 'stream' on client displayed in a window?  Resizable would be amazing too.
Possibly the only lacking feature I see which causes me to use Parsec still

**Comment by kisak-valve** [comment]
Hello @schtufbox, noted at https://github.com/flathub/com.valvesoftware.SteamLink#support, general questions and feature requests are being handled in the [Steam Link community forums](https://steamcommunity.com/app/353380/discussions/10/).
